version: '3.8'

services:
  web:
    image: fastapi-python-application
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - backend

networks:
  backend:
    driver: bridge
